name: Publish, Test, and Migrate to SmarterASP.NET

on:
  push:
    branches:
      - master
    paths:
      - 'back/**'

jobs:
  build_and_deploy:
    name: Build, Test, Migrate, and Deploy to SmarterASP.NET
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Install Entity Framework Core CLI
        run: dotnet tool install --global dotnet-ef --version 8.0.1

      - name: Restore dependencies
        run: dotnet restore ./back/MB.API/MB.API.csproj

      - name: Run API Tests
        run: dotnet test ./back/MB.API.Tests/MB.API.Tests.csproj

      - name: Run Application Tests
        run: dotnet test ./back/MB.Application.Tests/MB.Application.Tests.csproj

      - name: Run Domain Tests
        run: dotnet test ./back/MB.Domain.Tests/MB.Domain.Tests.csproj

      - name: Run Infrastructure Tests
        run: dotnet test ./back/MB.Infrastructure.Tests/MB.Infrastructure.Tests.csproj

      - name: Run Persistence Tests
        run: dotnet test ./back/MB.Persistence.Tests/MB.Persistence.Tests.csproj

      - name: Publish .NET project
        run: dotnet publish ./back/MB.API/MB.API.csproj -c Release -o ./publish

      - name: Apply EF Core Migrations
        run: dotnet ef database update --project ./back/MB.Persistence/MB.Persistence.csproj
        env:
          ConnectionStrings__DB: ${{ secrets.PRODUCTION_CONNECTION_STRING }}

      - name: Deploy to SmarterASP.NET
        uses: aarhusit/deploy@main
        with:
          csproj-filepath: ${{ secrets.PROJECT }}
          website-name: ${{ secrets.IIS_APP_NAME }}
          server-computer-name: ${{ secrets.MSDEPLOY_SERVICE_URL }}
          server-username: ${{ secrets.IIS_USER }}
          server-password: ${{ secrets.IIS_PASSWORD }}